language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

arch:
  - amd64
  - ppc64le

sudo: false

env:
  global:
    - COVERAGE_PROCESS_START=".coveragerc"

before_install:
  - pip install nose coverage

script:
  - ./docker_test.sh

after_success:
  - if [[ "$TRAVIS_CPU_ARCH" != "ppc64le" ]]; then pip install coveralls && coveralls; fi;
