language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

arch:
  - amd64
  - ppc64le

sudo: false

env:
  global:
    - COVERAGE_PROCESS_START=".coveragerc"

before_install:
  - pip install nose coverage
  - pip install coveralls || exit 0

script:
  - JSONRPCLIB_TEST_EXPECTED_LIB=json nosetests -v --with-coverage --cover-package=jsonrpclib tests
  - pip install ujson && (JSONRPCLIB_TEST_EXPECTED_LIB=ujson nosetests -v --with-coverage --cover-package=jsonrpclib tests/test_jsonlib.py ; pip uninstall -y ujson) || exit 0
  - pip install simplejson && (JSONRPCLIB_TEST_EXPECTED_LIB=simplejson nosetests -v --with-coverage --cover-package=jsonrpclib tests/test_jsonlib.py ; pip uninstall -y simplejson) || exit 0
  - pip install python-cjson && (JSONRPCLIB_TEST_EXPECTED_LIB=cjson nosetests -v --with-coverage --cover-package=jsonrpclib tests/test_jsonlib.py ; pip uninstall -y python-cjson) || exit 0

after_success:
  - coveralls || exit 0
